name: Run GitHub CLI Command

on:
  push:
    branches:
      - main

jobs:
  run-gh-cli:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up GitHub CLI
      - name: Install GitHub CLI
        uses: actions/setup-gh@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Run a GitHub CLI command
      - name: Run GitHub CLI Command
        run: |
          gh auth status
          gh repo view
          gh issue list
