name: Run GitHub CLI Command on Push


# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  run-gh-cli:
    runs-on: ubuntu-latest # Run on the latest Ubuntu environment
    container: ubuntu:latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PARETO_TOKEN }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
        
      # Step 2: Print "Hello, World!"
      - name: Print Hello, World!
        run: echo "Hello, World!"
          
      # Step 3: List files in the repository
      - name: List files in the repository
        run: ls -la
        
      # Step 4: Setup gh
      - name: Setup gh
        uses: wusatosi/setup-gh@v1
        
      # Step 5: Authenticate the GitHub CLI
      - name: Authenticate with GitHub CLI
        run: gh auth status # Check that authentication is successful
        
      # Step 6: Run a GitHub CLI command to list issues
      - name: List GitHub Issues
        run: |
          gh issue list
          gh version
          echo ${{ github.repository }}



