name: Run GitHub CLI Command on Push


# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  run-gh-cli:
    runs-on: ubuntu-latest # Run on the latest Ubuntu environment
    container: ubuntu:latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
        
      # Step 2: Print "Hello, World!"
      - name: Print Hello, World!
        run: echo "Hello, World!"
          
      # Step 3: List files in the repository
      - name: List files in the repository
        run: ls -la
        
      # Step 4: Setup gh
      - name: Setup gh
        uses: wusatosi/setup-gh@v1
        
      # Step 5: Authenticate the GitHub CLI
      - name: Authenticate with GitHub CLI
        run: gh auth status # Check that authentication is successful
        
      # Step 6: Run a GitHub CLI command to list issues
      - name: List GitHub Issues
        run: |
          gh issue list
          gh api graphql -f query="query {node(id: \"PVT_kwDOBpXwDs4AZl82\"){ ... on ProjectV2 {items(last: 2){ nodes{id fieldValues(first: 32){ __typename } content{ ...on Issue{title state createdAt author{login} labels(first: 10){nodes {name}}}} status: fieldValueByName(name:\"Status\") { ... on ProjectV2ItemFieldSingleSelectValue{name}} customer: fieldValueByName(name:\"Customer\") { ... on ProjectV2ItemFieldSingleSelectValue{name}} account_manager: fieldValueByName(name:\"Account Manager\") { ... on ProjectV2ItemFieldSingleSelectValue{name}} account_manager: fieldValueByName(name:\"Account Manager\") { ... on ProjectV2ItemFieldSingleSelectValue{name}} software_version: fieldValueByName(name:\"Software Version\") { ... on ProjectV2ItemFieldSingleSelectValue{name}}}}}}}"

