name: Run GitHub CLI Command on Push


# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  run-gh-cli:
    runs-on: ubuntu-latest # Run on the latest Ubuntu environment
    container: ubuntu:latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
        
      # Step 2: Print "Hello, World!"
      - name: Print Hello, World!
        run: echo "Hello, World!"
          
      # Step 3: List files in the repository
      - name: List files in the repository
        run: ls -la
        
      # Step 4: Setup gh
      - name: Setup gh
        uses: wusatosi/setup-gh@v1




