name: Run GitHub CLI Command on Push


# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  run-gh-cli:
    runs-on: ubuntu-latest # Run on the latest Ubuntu environment
    container: ubuntu:latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
        
      # Step 2: Print "Hello, World!"
      - name: Print Hello, World!
        run: echo "Hello, World!"
          
      # Step 3: List files in the repository
      - name: List files in the repository
        run: ls -la
        
      # Step 4: Setup gh
      - name: Setup gh
        uses: wusatosi/setup-gh@v1
        token: ${{ secrets.MY_PARETO_TOKEN }} # Use the GitHub token provided by Actions
        
      # Step 5: Authenticate the GitHub CLI
      - name: Authenticate with GitHub CLI
        run: gh auth status # Check that authentication is successful
        
      # Step 6: Run a GitHub CLI command to list issues
      - name: List GitHub Issues
        run: |
          gh issue list
          gh api graphql -f query="query{node(id: \"PVT_kwHOAh9Tc84Amrsu\") {... on ProjectV2 {items(first: 2) {nodes{id fieldValues(first: 8) {nodes{... on ProjectV2ItemFieldTextValue {text field {... on ProjectV2FieldCommon {name}}} ... on ProjectV2ItemFieldDateValue {date field {... on ProjectV2FieldCommon {name}}} ... on ProjectV2ItemFieldSingleSelectValue {name field {... on ProjectV2FieldCommon {name}}}}} content{... on DraftIssue {title body} ...on Issue {title assignees(first: 10) {nodes {login}}} ...on PullRequest {title assignees(first: 10) {nodes {login}}}}}}}}}"

