name: Run GitHub CLI Command on Push

# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  run-gh-cli:
    runs-on: ubuntu-latest # Run on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up GitHub CLI
      - name: Install GitHub CLI
        uses: actions/setup-gh@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token provided by Actions

      # Step 3: Authenticate the GitHub CLI
      - name: Authenticate with GitHub CLI
        run: gh auth status # Check that authentication is successful

      # Step 4: Run a GitHub CLI command to list issues
      - name: List GitHub Issues
        run: gh issue list
